-- ============================================================
-- 09-FINAL：渠道交易表全量重建（DROP + CREATE）
-- 用途：删除旧表，按最终精简结构重新创建（含分区）
-- 生成日期：2026-08-07
-- 字段命名规范：付款 pay_ / 收款 rec_ / 提现 withdraw_ / 银行卡 bank_card_
-- 前置条件：无（全新执行）
-- ============================================================
-- 字段范围：清晰字段化存储，无 MEDIUMTEXT 快照，无 version/request_hash
-- 每张表约 43-55 个字段（含退款表 original_* 字段）
-- 全部带 LINEAR KEY (tenant_id, store_id) PARTITIONS 30 分区

-- ==================== DROP（先删旧表）====================

DROP TABLE IF EXISTS `front_citic_transfer_transaction`;
DROP TABLE IF EXISTS `front_pingan_transfer_transaction`;
DROP TABLE IF EXISTS `front_citic_consume_transaction`;
DROP TABLE IF EXISTS `front_pingan_consume_transaction`;
DROP TABLE IF EXISTS `front_citic_refund_transaction`;
DROP TABLE IF EXISTS `front_pingan_refund_transaction`;
DROP TABLE IF EXISTS `front_citic_withdraw_transaction`;
DROP TABLE IF EXISTS `front_pingan_withdraw_transaction`;
DROP TABLE IF EXISTS `front_citic_platform_pay_transaction`;
DROP TABLE IF EXISTS `front_citic_platform_receive_transaction`;

-- ==================== CREATE（重建最终结构）====================

-- =============================================================================
-- Front 分银行、分交易业务渠道流水建表 SQL
-- 字符集：utf8mb4 / 排序规则：utf8mb4_general_ci / 引擎：InnoDB / 行格式：DYNAMIC
-- 共 10 张表：中信 6 张 + 平安 4 张
-- 字段类型规范见 09B 文档 §1
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. front_citic_transfer_transaction  中信转账渠道交易流水（capability=TRANSFER）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_citic_transfer_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '中信转账渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 TRANSFER',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源业务交易逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源业务交易主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源业务交易子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '业务系统本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店 ID',
  `pay_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '付款方电子账户号（原始值，未加密）',
  `pay_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '付款方名称',
  `rec_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '收款方电子账户号（原始值，未加密）',
  `rec_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '收款方名称',
  `amount`                            BIGINT        NOT NULL                COMMENT '转账金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '转账手续费，单位为人民币分',
  `refunded_amount`                   BIGINT        NOT NULL DEFAULT 0      COMMENT '该原交易累计确认退款金额，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等银行侧交易流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '中信业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '中信业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '中信原始交易状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化交易状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 中信转账渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 2. front_pingan_transfer_transaction  平安转账及转账授权渠道交易流水
--    capability 允许：TRANSFER / TRANSFER_AUTH / TRANSFER_AUTH_CODE_RESEND
-- -----------------------------------------------------------------------------
CREATE TABLE `front_pingan_transfer_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '平安转账渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT '能力编码：TRANSFER、TRANSFER_AUTH 或 TRANSFER_AUTH_CODE_RESEND',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源业务交易逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源业务交易主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源业务交易子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '业务系统本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店 ID',
  `pay_member_id`                  VARCHAR(100)  DEFAULT NULL            COMMENT '付款方商户会员编号',
  `pay_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '付款方电子账户号（原始值，未加密）',
  `pay_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '付款方名称',
  `rec_member_id`                  VARCHAR(100)  DEFAULT NULL            COMMENT '收款方商户会员编号',
  `rec_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '收款方电子账户号（原始值，未加密）',
  `rec_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '收款方名称',
  `amount`                            BIGINT        NOT NULL                COMMENT '转账或授权交易金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '平安转账手续费，单位为人民币分',
  `refunded_amount`                   BIGINT        NOT NULL DEFAULT 0      COMMENT '该原交易累计确认退款金额，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '平安协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '平安协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等银行侧交易流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '平安业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '平安业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '平安原始交易状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化交易状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 平安转账及转账授权渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 3. front_citic_consume_transaction  中信消费渠道交易流水（capability=CONSUME）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_citic_consume_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '中信消费渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 CONSUME',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源业务交易逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源业务交易主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源业务交易子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '业务系统本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店 ID',
  `pay_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '付款方电子账户号（原始值，未加密）',
  `pay_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '付款方名称',
  `rec_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '收款方电子账户号（原始值，未加密）',
  `rec_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '收款方名称',
  `amount`                            BIGINT        NOT NULL                COMMENT '消费金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '消费手续费，单位为人民币分',
  `refunded_amount`                   BIGINT        NOT NULL DEFAULT 0      COMMENT '该消费累计确认退款金额，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等银行侧交易流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '中信业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '中信业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '中信原始交易状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化交易状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 中信消费渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 4. front_pingan_consume_transaction  平安消费渠道交易流水（capability=CONSUME）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_pingan_consume_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '平安消费渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 CONSUME',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源业务交易逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源业务交易主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源业务交易子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '业务系统本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店 ID',
  `pay_member_id`                  VARCHAR(100)  DEFAULT NULL            COMMENT '付款方商户会员编号',
  `pay_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '付款方电子账户号（原始值，未加密）',
  `pay_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '付款方名称',
  `rec_member_id`                  VARCHAR(100)  DEFAULT NULL            COMMENT '收款方商户会员编号',
  `rec_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '收款方电子账户号（原始值，未加密）',
  `rec_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '收款方名称',
  `amount`                            BIGINT        NOT NULL                COMMENT '消费金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '平安消费手续费，单位为人民币分',
  `refunded_amount`                   BIGINT        NOT NULL DEFAULT 0      COMMENT '该消费累计确认退款金额，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '平安协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '平安协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等银行侧交易流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '平安业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '平安业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '平安原始交易状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化交易状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 平安消费渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 5. front_citic_refund_transaction  中信真退款渠道交易流水（capability=REFUND，bizFunc=23）
--    当前仅 original_biz_order_no/original_biz_sub_order_no 用于中信退款原交易定位；
--    其他 5 个 original_* 为可空兼容保留列，Handle 不读写。
-- -----------------------------------------------------------------------------
CREATE TABLE `front_citic_refund_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '中信退款渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 REFUND',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局退款渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源退款业务逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源退款业务主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源退款业务子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '退款业务本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '退款业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '退款业务子流水号或子订单号',
  `original_capability`               VARCHAR(20)   DEFAULT NULL            COMMENT '兼容保留列；中信当前退款路径不使用且不回填',
  `original_channel_transaction_id`   BIGINT        DEFAULT NULL            COMMENT '兼容保留列；中信当前退款路径不使用且不回填',
  `original_front_ssn`                VARCHAR(100)  DEFAULT NULL            COMMENT '兼容保留列；中信当前退款路径不使用且不回填',
  `original_biz_transaction_id`       VARCHAR(100)  DEFAULT NULL            COMMENT '兼容保留列；中信当前退款路径不使用且不回填',
  `original_biz_sub_transaction_id`   VARCHAR(100)  DEFAULT NULL            COMMENT '兼容保留列；中信当前退款路径不使用且不回填',
  `original_biz_order_no`             VARCHAR(100)  NOT NULL                COMMENT '当前中信退款实际使用的原业务主流水号',
  `original_biz_sub_order_no`         VARCHAR(100)  DEFAULT NULL            COMMENT '当前中信退款实际使用的原业务子流水号；应用层必填',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方业务门店 ID',
  `pay_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方电子账户号（原始值，未加密）',
  `pay_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方名称',
  `rec_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方电子账户号（原始值，未加密）',
  `rec_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方名称',
  `amount`                            BIGINT        NOT NULL                COMMENT '本次真退款金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '本次退款手续费，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '中信真退款业务编号 bizFunc，当前为 23',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等退款流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行退款日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行退款时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '中信业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '中信业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '中信原始退款状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化退款状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_original_transaction` (`original_capability`,`original_channel_transaction_id`),
  KEY `idx_front_original_ssn` (`original_front_ssn`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 中信真退款渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 6. front_pingan_refund_transaction  平安退款渠道交易流水（capability=REFUND）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_pingan_refund_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '平安退款渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 REFUND',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局退款渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源退款业务逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源退款业务主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源退款业务子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '退款业务本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '退款业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '退款业务子流水号或子订单号',
  `original_capability`               VARCHAR(20)   NOT NULL                COMMENT '原渠道交易能力，当前允许 TRANSFER 或 CONSUME',
  `original_channel_transaction_id`   BIGINT        NOT NULL                COMMENT '同银行原转账或消费渠道表记录主键',
  `original_front_ssn`                VARCHAR(100)  NOT NULL                COMMENT '原 Front 渠道交易流水号',
  `original_biz_transaction_id`       VARCHAR(100)  NOT NULL                COMMENT '原业务交易主表记录 ID',
  `original_biz_sub_transaction_id`   VARCHAR(100)  DEFAULT NULL            COMMENT '原业务交易子表或明细表记录 ID',
  `original_biz_order_no`             VARCHAR(100)  NOT NULL                COMMENT '原业务主流水号或主订单号',
  `original_biz_sub_order_no`         VARCHAR(100)  DEFAULT NULL            COMMENT '原业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方业务门店 ID',
  `pay_member_id`                  VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方商户会员编号',
  `pay_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方电子账户号（原始值，未加密）',
  `pay_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '退款付款方名称',
  `rec_member_id`                  VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方商户会员编号',
  `rec_account_id`                 VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方电子账户号（原始值，未加密）',
  `rec_name`                       VARCHAR(100)  DEFAULT NULL            COMMENT '退款收款方名称',
  `amount`                            BIGINT        NOT NULL                COMMENT '本次退款金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '本次退款手续费，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '平安协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '平安退款协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等退款流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行退款日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行退款时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '平安业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '平安业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '平安原始退款状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化退款状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_original_transaction` (`original_capability`,`original_channel_transaction_id`),
  KEY `idx_front_original_ssn` (`original_front_ssn`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 平安退款渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 7. front_citic_withdraw_transaction  中信提现渠道交易流水（capability=WITHDRAW）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_citic_withdraw_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '中信提现渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 WITHDRAW',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局提现渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源提现业务逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源提现业务主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源提现业务子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '提现业务本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '提现业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '提现业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现收款方业务门店 ID',
  `withdraw_account_id`              VARCHAR(100)  DEFAULT NULL            COMMENT '提现电子账户号（原始值，未加密）',
  `withdraw_account_name`            VARCHAR(100)  DEFAULT NULL            COMMENT '提现账户名称',
  `bank_card_no`                     VARCHAR(100)  DEFAULT NULL            COMMENT '提现银行卡号（原始值，未加密）',
  `bank_card_holder_name`            VARCHAR(100)  DEFAULT NULL            COMMENT '银行卡持卡人姓名',
  `amount`                            BIGINT        NOT NULL                COMMENT '提现金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '提现手续费，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '中信提现协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等提现流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行提现日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行提现时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '中信业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '中信业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '中信原始提现状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化提现状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 中信提现渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 8. front_pingan_withdraw_transaction  平安提现渠道交易流水（capability=WITHDRAW）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_pingan_withdraw_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '平安提现渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 WITHDRAW',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局提现渠道流水号，同时作为本次银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源提现业务逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源提现业务主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源提现业务子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '提现业务本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '提现业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '提现业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '提现收款方业务门店 ID',
  `withdraw_member_id`               VARCHAR(100)  DEFAULT NULL            COMMENT '提现商户会员编号',
  `withdraw_account_id`              VARCHAR(100)  DEFAULT NULL            COMMENT '提现电子账户号（原始值，未加密）',
  `withdraw_account_name`            VARCHAR(100)  DEFAULT NULL            COMMENT '提现账户名称',
  `bank_card_no`                     VARCHAR(100)  DEFAULT NULL            COMMENT '提现银行卡号（原始值，未加密）',
  `bank_card_holder_name`            VARCHAR(100)  DEFAULT NULL            COMMENT '银行卡持卡人姓名',
  `amount`                            BIGINT        NOT NULL                COMMENT '提现金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '平安提现手续费，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '平安协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '平安提现协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等提现流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行提现日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行提现时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '平安业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '平安业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '平安原始提现状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化提现状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 平安提现渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 9. front_citic_platform_pay_transaction  中信平台付款渠道交易流水（capability=PLATFORM_PAY）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_citic_platform_pay_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '中信平台付款渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 PLATFORM_PAY',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局平台付款渠道流水号，同时作为银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源平台付款业务逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源平台付款业务主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源平台付款业务子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '平台付款业务本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '平台付款业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '平台付款业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店 ID',
`rec_account_id` VARCHAR(100) DEFAULT NULL COMMENT '收款方电子账户号（平台付款时用户是收款方）（原始值，未加密）',
  `rec_name` VARCHAR(200) DEFAULT NULL COMMENT '收款方电子账户户名',
  `amount`                            BIGINT        NOT NULL                COMMENT '平台付款金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '平台付款手续费，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '中信平台付款协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等平台付款流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '中信业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '中信业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '中信原始平台付款状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化平台付款状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 中信平台付款渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


-- -----------------------------------------------------------------------------
-- 10. front_citic_platform_receive_transaction  中信平台收款渠道交易流水（capability=PLATFORM_RECEIVE）
-- -----------------------------------------------------------------------------
CREATE TABLE `front_citic_platform_receive_transaction` (
  `id`                                BIGINT        NOT NULL                COMMENT '中信平台收款渠道记录主键，由 Front 生成分布式 ID',
  `tenant_id`                         VARCHAR(100)  NOT NULL                COMMENT 'SaaS 租户标识',
  `store_id`                          VARCHAR(100)  NOT NULL                COMMENT '发起本次调用的业务门店 ID',
  `data_source_id`                    VARCHAR(30)   NOT NULL DEFAULT ''     COMMENT '数据源实例标识（如 ds_0/ds_2），记录数据所在库实例',
  `capability`                        VARCHAR(20)   NOT NULL                COMMENT 'Front 能力编码；本表固定为 PLATFORM_RECEIVE',
  `front_ssn`                         VARCHAR(100)  NOT NULL                COMMENT 'Front 全局平台收款渠道流水号，同时作为银行请求 transSsn',
  `front_query_id`                    VARCHAR(100)  DEFAULT NULL            COMMENT '返回业务系统的 Front 查询标识',
  `biz_system_code`                   VARCHAR(100)  NOT NULL                COMMENT '来源业务系统编码',
  `biz_transaction_type`              VARCHAR(20)   NOT NULL                COMMENT '来源平台收款业务逻辑类型，不保存物理表名',
  `biz_transaction_id`                VARCHAR(100)  NOT NULL                COMMENT '来源平台收款业务主表记录 ID',
  `biz_sub_transaction_id`            VARCHAR(100)  DEFAULT NULL            COMMENT '来源平台收款业务子表或明细表记录 ID',
  `biz_request_no`                    VARCHAR(100)  NOT NULL                COMMENT '平台收款业务本次调用唯一号',
  `biz_order_no`                      VARCHAR(100)  NOT NULL                COMMENT '平台收款业务主流水号或主订单号',
  `biz_sub_order_no`                  VARCHAR(100)  DEFAULT NULL            COMMENT '平台收款业务子流水号或子订单号',
  `pay_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店编码',
  `pay_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '付款方业务门店 ID',
  `rec_store_no`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店编码',
  `rec_store_id`                      VARCHAR(100)  DEFAULT NULL            COMMENT '收款方业务门店 ID',
`pay_account_id` VARCHAR(100) DEFAULT NULL COMMENT '付款方电子账户号（平台收款时用户是付款方）（原始值，未加密）',
  `pay_name` VARCHAR(200) DEFAULT NULL COMMENT '付款方电子账户户名',
  `amount`                            BIGINT        NOT NULL                COMMENT '平台收款金额，单位为人民币分',
  `fee`                               BIGINT        NOT NULL DEFAULT 0      COMMENT '平台收款手续费，单位为人民币分',
  `currency`                          VARCHAR(20)   NOT NULL DEFAULT 'CNY'  COMMENT '币种',
  `bank_channel_no`                   VARCHAR(20)   DEFAULT NULL            COMMENT '中信协议渠道编号 chnlNo',
  `bank_biz_func`                     VARCHAR(20)   DEFAULT NULL            COMMENT '中信平台收款协议业务编号 bizFunc',
  `external_platform_ssn`             VARCHAR(100)  DEFAULT NULL            COMMENT '银行 reserve 中的外联平台流水 laasSsn',
  `bank_query_id`                     VARCHAR(100)  DEFAULT NULL            COMMENT '电子钱包或银行返回的 queryId',
  `bank_user_ssn`                     VARCHAR(100)  DEFAULT NULL            COMMENT '银行返回的 USER_SSN 等平台收款流水',
  `bank_trans_date`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易日期，字符串格式 yyyyMMdd',
  `bank_trans_time`                   VARCHAR(20)   DEFAULT NULL            COMMENT '银行交易时间，字符串格式 HHmmss',
  `wallet_resp_code`                  VARCHAR(20)   DEFAULT NULL            COMMENT '电子钱包平台层原始响应码 errCode',
  `wallet_resp_desc`                  VARCHAR(512)  DEFAULT NULL            COMMENT '电子钱包平台层原始响应说明 errInfo',
  `bank_resp_code`                    VARCHAR(20)   DEFAULT NULL            COMMENT '中信业务层原始响应码 sysRespCode',
  `bank_resp_desc`                    VARCHAR(512)  DEFAULT NULL            COMMENT '中信业务层原始响应说明 sysRespDesc',
  `bank_status`                       VARCHAR(20)   DEFAULT NULL            COMMENT '中信原始平台收款状态，仅供查询与审计',
  `reserve1`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 1，稳定后迁移为明确业务列',
  `reserve2`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 2，稳定后迁移为明确业务列',
  `reserve3`                          VARCHAR(1024) DEFAULT NULL            COMMENT '临时扩展字段 3，稳定后迁移为明确业务列',
  `front_status`                      VARCHAR(20)   NOT NULL DEFAULT 'INIT' COMMENT 'Front 归一化平台收款状态',
  `bank_responded_at`                 DATETIME      DEFAULT NULL            COMMENT '收到银行同步响应时间',
  `create_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '创建者',
  `create_time`                       DATETIME      DEFAULT NULL            COMMENT '创建时间',
  `update_by`                         VARCHAR(64)   DEFAULT NULL            COMMENT '更新者',
  `update_time`                       DATETIME      DEFAULT NULL            COMMENT '更新时间',
  PRIMARY KEY (`id`, `tenant_id`, `store_id`),
  KEY `idx_front_ssn` (`front_ssn`),
  KEY `idx_front_data_source` (`tenant_id`,`data_source_id`),
  KEY `idx_front_business_main` (`tenant_id`,`biz_system_code`,`biz_transaction_type`,`biz_transaction_id`),
  KEY `idx_front_business_sub` (`tenant_id`,`biz_system_code`,`biz_sub_transaction_id`),
  KEY `idx_front_biz_order` (`tenant_id`,`biz_order_no`,`biz_sub_order_no`),
  KEY `idx_front_bank_query` (`bank_query_id`),
  KEY `idx_front_bank_user_ssn` (`bank_user_ssn`),
  KEY `idx_front_status_time` (`tenant_id`,`front_status`,`update_time`),
  KEY `idx_front_store_time` (`tenant_id`,`store_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='Front 中信平台收款渠道交易流水' PARTITION BY LINEAR KEY (`tenant_id`, `store_id`) PARTITIONS 30;


SELECT TABLE_NAME, TABLE_COLLATION, ENGINE, TABLE_COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME LIKE 'front\_%\_transaction'
ORDER BY TABLE_NAME;


SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, DATETIME_PRECISION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME LIKE 'front\_%\_transaction'
  AND (DATA_TYPE IN ('char') OR DATETIME_PRECISION = 3
       OR CHARACTER_MAXIMUM_LENGTH NOT IN (20, 100, 512, 1024) AND CHARACTER_MAXIMUM_LENGTH IS NOT NULL)
ORDER BY TABLE_NAME, COLUMN_NAME;
